### ISSUE TITLE
social.tcpcat.net should be safe now

### ISSUE THREAD

**Issue by noblereign** [Mastodon-DE/blocklists#16]
i alerted the instance owner over telegram and they just replied to me thanking me for the notice. i checked and sure enough their local timeline is clean, the spam bot accounts deleted, and the registrations are set to requests now! 👍
![image](https://github.com/Mastodon-DE/blocklists/assets/2935979/3a057639-a591-494c-8831-c3c85df00164)

**Comment by spirillen** [comment]
Thanks for your effort and report.

Will add it to https://github.com/Mastodon-DE/blocklists/pull/18

**Comment by ErikUden** [comment]
Removed it!
