### ISSUE TITLE
Add `tambayan.us`

### ISSUE THREAD

**Issue by craftxbox** [Mastodon-DE/blocklists#17]
This instance is actively emitting spam but is not listed.

**Comment by spirillen** [comment]
That one is listed here: https://kb.mypdns.org/issue/MR-1/Spam-bots

I'll add it to my MR...

**Comment by spirillen** [comment]
Was added in 341ee497b11ae5e727a07ec347f093d7096d1aae

**Comment by craftxbox** [comment]
Odd, i cant see it in the .MD?

**Comment by spirillen** [comment]
Nope, it is listed in the csv and domains only lists. but if I remember it right I did add it to the .md in my MR
