### ISSUE TITLE
New instances to be added from reports to the Pawb.Social groups

### ISSUE THREAD

**Issue by JoshuaKimsey** [Mastodon-DE/blocklists#4]
I'm sure there are repeats with others already on the list. I just have so many to report that I'm not going to try and do sorting on my end. It was apparently an active Sunday... >.> 

Some of these may have already been resolved too, since these stretch back to earlier this morning.

As of 9 PM EST, Feb 18th, 2024.

independent-media.co.uk
cryptodon.lol
beyond.forum
e.fo
terere.social
folksocial.org
westen.social
nycity.social
social.consoledated.com
tcpcat.net
graeber.social
electroverse.tech
tech.retrotalk.live
daotodon.me
mastodon.my
social.cezeri.tech
tootnet.nl
onion.social (numerous reports)
academia.pub
portside.social
sotl.social
scfzfilm.org
discourse.helenprejean.org
kernkraft.social (numerous reports)
mastodon.dragonbox.de
cmm.fyi
fusionpros.social
zettel.haus
mastodon.ashevillains.org
airwaves.social
forum-lucifer.com
witten.social
smooth.guru
nafo.uk
mastodon.wg0.xyz
onion.social
portside.social
waterlily.tokyo
bondsdogs.com
phyrexia.ru
social.foederiert.de
mastodon.snmsoc.org
m.corduba.tech
mastdn.social
cryptodon.lol
besties.com
westen.social
i.transmit.love (Targeted Lemmy)
cmm.fyi (Targeted Lemmy)

If you want to just leave this issue open, I can file more reports here further down to help try and kept up with what's coming in.

**Comment by JoshuaKimsey** [comment]
As of 3AM EST, Feb 19th, 2024.

waterlily.tokyo
don.neet.co.jp
hdty.in
i.transmit.love
edusocial.it
besties.com
owo.town
thewiring.com
nycity.social
digitaldata.social
estrogen.cat
bondsdogs.com
educhat.social
mentalhealth-masto.com
phyrexia.ru
discourse.helenprejean.org
kommunismus.social
mastodon.svgun.ru
cherryberry.pink
mastodon.mg
kokuusa.club
westen.social
terere.social
gervtuber.de
nafo.uk
mastodon.wg0.xyz
social.cezeri.tech
mastdn.social
toot.poedelwitz.de
edusocial.it
mastodon.zorqz.com

**Comment by ErikUden** [comment]
I'll work on it.

**Comment by ErikUden** [comment]
Done in latest update.
